### ISSUE TITLE
Latest Demyx version does not create SSL certificate on subdomains

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [demyxsh/demyx#36]
On a fresh install with the latest demyx version, when trying to spin up a new wordpress app with the command:
`demyx run evolvium.evoptt.com --ssl=true --php=8.2` 
it reports the error: 
`[2024-03-15-02:56:17] [ERROR] --ssl-wildcard is not supported with subdomains`

My DEMYX host file has the following vars changed :

```
DEMYX_AUTH_USERNAME=myemail@email.com
DEMYX_AUTH_PASSWORD=mypassword
DEMYX_TRAEFIK_SSL-true
DEMYX_CF_KEY=my_cloudflare_global_api_key
DEMYX_DOMAIN=evolvium.evoptt.com
DEMYX_EMAIL=myemail@email.com
DEMYX_IP=my_vps_ip
```

When DEMYX_CF_KEY is reverted to `false`, then the error message for the same command as before is:
`[2024-03-15-03:02:46] [ERROR] Please update DEMYX_DOMAIN, DEMYX_EMAIL, and/or DEMYX_CF_KEY on the host`

How can this be fixed?

VPS
---
- Ubuntu 22.04.4
- Kernel: Linux instance-20240315-0956 6.5.0-1018-oracle
- 2 CPU cores, 1GB RAM

Thanks!

**Comment by demyxco** [comment]
@Theofilos-Chamalis I have pushed a new image in the Docker hub that fixes this issue. You will need to provide `DEMYX_CF_KEY` if you do want to use `--ssl-wildcard` though.  I will release 1.8.1 soon but here's how to solve it now:

- Update the Demyx image: `demyx pull demyx`
- Restart the demyx container: `demyx host restart`
- Then rerun the command: `demyx run evolvium.evoptt.com --ssl=true --php=8.2`

**Comment by Theofilos-Chamalis** [comment]
@demyxco Thanks for the quick reply!

I have tried the steps described above: 
1. Changed `DEMYX_DOMAIN`, `DEMYX_EMAIL`, `DEMYX_TELEMETRY`, `DEMYX_AUTH_USERNAME`, `DEMYX_AUTH_PASSWORD`, `DEMYX_AUTH_CPU`, `DEMYX_MEM`
2. Performed `demyx pull demyx` and `demyx host restart`
3. Rerun the command `demyx run evolvium.evoptt.com --ssl=true --php=8.2`

but was still greeted with the same error: 
`[2024-03-16-14:36:40] [ERROR] Please update DEMYX_DOMAIN, DEMYX_EMAIL, and/or DEMYX_CF_KEY on the host`

Q1: I just need an ssl certificate for the subdomain `evolvium.evoptt.com` . Do I need to enable the --ssl-wildcard option?
Q2: What DEMYX_CF_KEY stands for? Is it for the Cloudflare API Token, Cloudflare Global API Key or Cloudflare Origin CA Key?
Q3: Do the options `DEMYX_IP`, `DEMYX_HOSTNAME`, `DEMYX_SMTP`, `DEMYX_CODE_SSL`, `DEMYX_TRAEFIK_SSL` play any role in this issue?

**Comment by demyxco** [comment]
Hi, sorry for the delay. The error was my fault due to the wrong if statement logic. The error should be fix now and was confirmed by someone in the Discord community. Please rerun those 3 commands:

- `demyx pull demyx`
- `demyx host restart`
- `demyx run evolvium.evoptt.com --ssl --php=8.2`

Should give Traefik about a minute or so to issue the certificate.

> Do I need to enable the --ssl-wildcard option?

No, it's not necessary for just regular SSL.

> What does the `DEMYX_CF_KEY` stand for?

It requires the Global API Key.

> Do the options `DEMYX_IP`, `DEMYX_HOSTNAME`, `DEMYX_SMTP`, `DEMYX_CODE_SSL`, `DEMYX_TRAEFIK_SSL` play any role in this issue?

- `DEMYX_IP` is only used for IP whitelisting, has no relations to SSL
- `DEMYX_HOSTNAME` is mostly used for vanity purposes when you open a shell into any of the demyx containers
- `DEMYX_SMTP` is for email notifications
- `DEMYX_CODE_SSL` is to enable SSL for the Demyx Browser only, not related to using `demyx run` but still requires `DEMYX_DOMAIN` and `DEMYX_EMAIL`
- `DEMYX_TRAEFIK_SSL` enables SSL for the Traefik dashboard, same conditions as `DEMYX_CODE_SSL`

Please read more on the [Knowledge Base > Environment Variables](https://demyx.sh/kb/getting-started/environment-variables-getting-started/)

**Comment by Theofilos-Chamalis** [comment]
Thanks for the quick reply and for your hard work on the project @demyxco !
I can confirm that this issue is now resolved and I'm closing it :) .
